### PR TITLE
Cache #188 - Added caching to get_raw_file() with lru_cache

### PR DESCRIPTION
**Pull request by clamytoe**
## Description

Added caching to get_raw_file() with lru_cache

## Context

For issue #188 

## Additional Information

Only cached the results from get_raw_file() since that is the only thing that is reading from disk. Everything else should already be in memory, so should not be an issue. Hope this is what you had in mind.

### CODE REVIEW

**Comment by RDIL** [comment]
Is this included in the python standard library?

**Comment by clamytoe** [comment]
Yes, this is in the standard library.

**Comment by RDIL** [comment]
Thank you!

**Comment by clamytoe** [comment]
You're welcome. Nice little project you have here. Will definitely start using it in mine!

**Comment by RDIL** [comment]
Thanks :D 
I’ll trigger a release build for these changes once I get home.

**Comment by clamytoe** [comment]
No problem. Will pull the update later tonight when I get home as well.

**Pull request merged**
